#!/usr/bin/env python
"""
nagios-helper - Reads a nagios.cmd fifo for external check commands and sends them to a remote NSCA daemon

Author: Lars Larsson <lars@lars.la>
"""

import multiprocessing
import os
import time
from readthread import ReadThread
from sendthread import SendThread

fifoname = "nagios.cmd"
nsca_host = "localhost"

MAXTHREADS = 10

threads = []

def create_fifo(fifoname):
    os.mkfifo(fifoname)

if __name__=="__main__":
    if not os.path.exists(fifoname):
        create_fifo(fifoname)

    """ Initialize queue """
    queue = multiprocessing.Queue()

    try:
        """ Start the read thread """
        threads.append(ReadThread(0, fifoname, queue))
        threads[0].start()

        """ Start our send threads """
        for i in range(1, MAXTHREADS):
            threads.append(SendThread(i, queue, nsca_host))
            threads[i].start()

        while 1:
            time.sleep(10)
    except KeyboardInterrupt:
        print "Got KeyboardInterrupt"
        for i in range(0, MAXTHREADS):
            threads[i].terminate()